name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Timestamp Action
      uses: nanzm/get-time-action@v1.1
    - name: make
      run: make
    - name: make unit_tests
      run: make unit_tests
